// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8PzMTfk7q6EMnzap3u5sWAJkmRa0pHpw',
    appId: '1:832872727596:android:dffe78c2830c836b2a3d89',
    messagingSenderId: '832872727596',
    projectId: 'animepro-f76b1',
    storageBucket: 'animepro-f76b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkH6_bUL_u0jglOjkatcPCy-jSHmyte8',
    appId: '1:832872727596:ios:a055ceb8b79f1b572a3d89',
    messagingSenderId: '832872727596',
    projectId: 'animepro-f76b1',
    storageBucket: 'animepro-f76b1.appspot.com',
    iosBundleId: 'com.example.vinlandsagaPro',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAULK3m5Wjlo9pz1SxNb7lkyF4-qVbHEGI',
    appId: '1:832872727596:web:42f600a493d6babe2a3d89',
    messagingSenderId: '832872727596',
    projectId: 'animepro-f76b1',
    authDomain: 'animepro-f76b1.firebaseapp.com',
    storageBucket: 'animepro-f76b1.appspot.com',
    measurementId: 'G-MQG782F451',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpkH6_bUL_u0jglOjkatcPCy-jSHmyte8',
    appId: '1:832872727596:ios:a055ceb8b79f1b572a3d89',
    messagingSenderId: '832872727596',
    projectId: 'animepro-f76b1',
    storageBucket: 'animepro-f76b1.appspot.com',
    iosBundleId: 'com.example.vinlandsagaPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAULK3m5Wjlo9pz1SxNb7lkyF4-qVbHEGI',
    appId: '1:832872727596:web:dadd10feba36cb882a3d89',
    messagingSenderId: '832872727596',
    projectId: 'animepro-f76b1',
    authDomain: 'animepro-f76b1.firebaseapp.com',
    storageBucket: 'animepro-f76b1.appspot.com',
    measurementId: 'G-J9N70MNLSG',
  );

}